version: '3'
services:
  nginx:
    image: nginx:1.20.1
    # ports:
    #   - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    restart: always
    links:
      - php
    depends_on:
      - php

  php:
  # 通过dockerfile构建的test_epay镜像
    image: test_epay
    restart: always
    working_dir: /var/www/html
    links:
      - mysql   
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6.50
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
      - MYSQL_DATABASE=epay
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  cftunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    links:
      - nginx
    depends_on:
      - nginx
    restart: always

